wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.41.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714471660.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.16.6
      6: 4.41.0.dev0
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
